name: Terraform CI

on:
- pull_request

jobs:
  terraform:
    name: "Terraform Lint/Validate"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -recursive -diff=true -check=true .
